server:
  port: 8080
spring:
  application:
    name: food-labeling
  datasource:
    url: jdbc:postgresql://localhost:5432/food_labeling
    username: jobbene
    password: api
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
