INSERT INTO food (food_id, food_name, created_at, updated_at) VALUES
  (1, 'Avocado', current_timestamp, current_timestamp),
  (2, 'Banana', current_timestamp, current_timestamp),
  (3, 'Carrot', current_timestamp, current_timestamp),
  (4, 'Dragonfruit', current_timestamp, current_timestamp),
  (5, 'Eggplant', current_timestamp, current_timestamp),
  (6, 'Fig', current_timestamp, current_timestamp),
  (7, 'Grapes', current_timestamp, current_timestamp),
  (8, 'Honeydew', current_timestamp, current_timestamp),
  (9, 'Iceberg Lettuce', current_timestamp, current_timestamp),
  (10, 'Jackfruit', current_timestamp, current_timestamp),
  (11, 'Kiwi', current_timestamp, current_timestamp),
  (12, 'Lemon', current_timestamp, current_timestamp),
  (13, 'Mango', current_timestamp, current_timestamp),
  (14, 'Nectarine', current_timestamp, current_timestamp),
  (15, 'Orange', current_timestamp, current_timestamp),
  (16, 'Papaya', current_timestamp, current_timestamp),
  (17, 'Quince', current_timestamp, current_timestamp),
  (18, 'Raspberry', current_timestamp, current_timestamp),
  (19, 'Strawberry', current_timestamp, current_timestamp),
  (20, 'Tomato', current_timestamp, current_timestamp),
  (21, 'Ugli Fruit', current_timestamp, current_timestamp),
  (22, 'Vanilla Bean', current_timestamp, current_timestamp),
  (23, 'Watermelon', current_timestamp, current_timestamp),
  (24, 'Xigua', current_timestamp, current_timestamp),
  (25, 'Yam', current_timestamp, current_timestamp),
  (26, 'Zucchini', current_timestamp, current_timestamp),
  (27, 'Apple', current_timestamp, current_timestamp),
  (28, 'Blueberry', current_timestamp, current_timestamp),
  (29, 'Cantaloupe', current_timestamp, current_timestamp),
  (30, 'Daikon', current_timestamp, current_timestamp),
  (31, 'Endive', current_timestamp, current_timestamp),
  (32, 'Fennel', current_timestamp, current_timestamp),
  (33, 'Ginger', current_timestamp, current_timestamp),
  (34, 'Horseradish', current_timestamp, current_timestamp),
  (35, 'Indian Fig', current_timestamp, current_timestamp),
  (36, 'Jalapeno', current_timestamp, current_timestamp),
  (37, 'Kale', current_timestamp, current_timestamp),
  (38, 'Leek', current_timestamp, current_timestamp),
  (39, 'Mandarin', current_timestamp, current_timestamp),
  (40, 'Napa Cabbage', current_timestamp, current_timestamp),
  (41, 'Okra', current_timestamp, current_timestamp),
  (42, 'Parsnip', current_timestamp, current_timestamp),
  (43, 'Radish', current_timestamp, current_timestamp),
  (44, 'Spinach', current_timestamp, current_timestamp),
  (45, 'Turnip', current_timestamp, current_timestamp),
  (46, 'Ube', current_timestamp, current_timestamp),
  (47, 'Vidalia Onion', current_timestamp, current_timestamp),
  (48, 'Watercress', current_timestamp, current_timestamp),
  (49, 'Yuzu', current_timestamp, current_timestamp),
  (50, 'Zestar Apple', current_timestamp, current_timestamp),
  (51, 'Artichoke', current_timestamp, current_timestamp),
  (52, 'Broccoli', current_timestamp, current_timestamp),
  (53, 'Chili Pepper', current_timestamp, current_timestamp),
  (54, 'Dill', current_timestamp, current_timestamp),
  (55, 'Elderberry', current_timestamp, current_timestamp),
  (56, 'Feijoa', current_timestamp, current_timestamp),
  (57, 'Gala Apple', current_timestamp, current_timestamp),
  (58, 'Habanero', current_timestamp, current_timestamp),
  (59, 'Italian Plum', current_timestamp, current_timestamp),
  (60, 'Jicama', current_timestamp, current_timestamp),
  (61, 'Kiwano', current_timestamp, current_timestamp),
  (62, 'Lime', current_timestamp, current_timestamp),
  (63, 'Mulberry', current_timestamp, current_timestamp),
  (64, 'Naranjilla', current_timestamp, current_timestamp),
  (65, 'Olive', current_timestamp, current_timestamp),
  (66, 'Peach', current_timestamp, current_timestamp),
  (67, 'Quinoa Sprout', current_timestamp, current_timestamp),
  (68, 'Rambutan', current_timestamp, current_timestamp),
  (69, 'Soursop', current_timestamp, current_timestamp),
  (70, 'Tangerine', current_timestamp, current_timestamp),
  (71, 'Ulluco', current_timestamp, current_timestamp),
  (72, 'Velvet Bean', current_timestamp, current_timestamp),
  (73, 'Wasabi', current_timestamp, current_timestamp),
  (74, 'Xanthan Root', current_timestamp, current_timestamp),
  (75, 'Yarrow', current_timestamp, current_timestamp),
  (76, 'Zedoary', current_timestamp, current_timestamp),
  (77, 'Almond', current_timestamp, current_timestamp),
  (78, 'Brazil Nut', current_timestamp, current_timestamp),
  (79, 'Cashew', current_timestamp, current_timestamp),
  (80, 'Date', current_timestamp, current_timestamp),
  (81, 'Eucalyptus Leaf', current_timestamp, current_timestamp),
  (82, 'Figleaf Gourd', current_timestamp, current_timestamp),
  (83, 'Grapefruit', current_timestamp, current_timestamp),
  (84, 'Hazelnut', current_timestamp, current_timestamp),
  (85, 'Ice Plant', current_timestamp, current_timestamp),
  (86, 'Jujube', current_timestamp, current_timestamp),
  (87, 'Kumquat', current_timestamp, current_timestamp),
  (88, 'Lychee', current_timestamp, current_timestamp),
  (89, 'Medlar', current_timestamp, current_timestamp),
  (90, 'Nutmeg', current_timestamp, current_timestamp),
  (91, 'Oregano', current_timestamp, current_timestamp),
  (92, 'Pineapple', current_timestamp, current_timestamp),
  (93, 'Quararibea', current_timestamp, current_timestamp),
  (94, 'Rosemary', current_timestamp, current_timestamp),
  (95, 'Sage', current_timestamp, current_timestamp),
  (96, 'Tamarind', current_timestamp, current_timestamp),
  (97, 'Uva Ursi', current_timestamp, current_timestamp),
  (98, 'Vanilla Pod', current_timestamp, current_timestamp),
  (99, 'Walnut', current_timestamp, current_timestamp),
  (100, 'Ximenia', current_timestamp, current_timestamp);
